image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: $CI_PROJECT_ID
    paths:
      - .gradle
      - build

test:
  stage: test
  script:
    - gradle --build-cache check
    - cat build/reports/jacoco/test/html/index.html
  cache:
    key: $CI_JOB_NAME
    paths:
      - .gradle
      - build

bintray:
  only:
    - master
  stage: deploy
  script: gradle bintray
  cache:
    key: $CI_PROJECT_ID
    policy: pull
    paths:
      - .gradle
      - build

pages:
  only:
    - master
  stage: deploy
  script: mv build/docs/javadoc public
  artifacts:
    paths:
      - public
  cache:
    key: $CI_PROJECT_ID
    policy: pull
    paths:
      - build/docs/
