image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: $CI_PROJECT_ID
    paths:
      - .gradle
      - build

test:
  stage: test
  script:
    - gradle --build-cache check
    - cat build/reports/jacoco/test/html/index.html
  cache:
    key: $CI_JOB_NAME
    paths:
      - .gradle
      - build

bintray:
  only:
    - master
  stage: deploy
  script: gradle bintray
  cache:
    key: $CI_PROJECT_ID
    policy: pull
    paths:
      - .gradle
      - build

docs:
  only:
    - master
  image: alpine:3.6
  stage: deploy
  script:
    - apk update
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - ssh-keyscan -p $SSH_PORT $SSH_ADDRESS >> ~/.ssh/known_hosts
    - echo "put -r build/docs/javadocs /var/www/elypiai" > run.sh
    - sftp -b run.sh -oPort=$SSH_PORT $SSH_USER@$SSH_ADDRESS
  cache:
    key: $CI_PROJECT_ID
    policy: pull
    paths:
      - build

